# .github/workflows/gh-pages.yml
name: Publish Hugo site to gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Grab your code
      - uses: actions/checkout@v3
        with:
          submodules: true

      # 2) Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.2'
          extended: true

      # 3) Build the site
      - name: Build
        run: hugo --minify

      # 4) Deploy `public/` to the gh-pages branch
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./public
          publish_branch: gh-pages
          # GITHUB_TOKEN is provided automatically
          github_token: ${{ secrets.GITHUB_TOKEN }}
