name: Publish Hugo site to gh-pages

# grant write to repo contents (incl. gh-pages)
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # double-confirm at job level
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # so you have full history
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.2'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./public
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
